# Prometheus configuration for Sentiment Analysis monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    service: 'sentiment-analysis'
    environment: 'production'

rule_files:
  - "sentiment-rules.yml"

scrape_configs:
  # Sentiment API metrics
  - job_name: 'sentiment-api'
    static_configs:
      - targets: ['sentiment-api:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093