name: Documentation Issue
description: Report an issue with documentation
title: "[DOCS]: "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details about the documentation issue.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Broken link
        - Typo/Grammar
        - Example not working
        - API documentation
        - Installation guide
        - Tutorial/Guide
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located? (URL, file path, section)
      placeholder: "https://github.com/terragon-labs/agentic-dev-orchestrator/blob/main/README.md#installation"
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the documentation issue in detail
      placeholder: "The installation instructions are missing..."
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: "I suggest adding..."

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terragon-labs/agentic-dev-orchestrator/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true