# Type stubs for ADO CLI module

from typing import Any, Dict, List, Optional

def cmd_init() -> None: ...
def cmd_run() -> None: ...
def cmd_status() -> None: ...
def cmd_discover() -> None: ...
def cmd_help() -> None: ...
def main() -> None: ...